# Generated by Django 3.0.2 on 2020-03-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
